/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/abelB.glb 
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/abelB.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature' rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <group name='body'>
            <skinnedMesh
              name='bodymesh'
              geometry={nodes.bodymesh.geometry}
              material={materials['Material.003']}
              skeleton={nodes.bodymesh.skeleton}
            />
            <skinnedMesh
              name='bodymesh_1'
              geometry={nodes.bodymesh_1.geometry}
              material={materials.bota}
              skeleton={nodes.bodymesh_1.skeleton}
            />
            <skinnedMesh
              name='bodymesh_2'
              geometry={nodes.bodymesh_2.geometry}
              material={materials.body}
              skeleton={nodes.bodymesh_2.skeleton}
            />
            <skinnedMesh
              name='bodymesh_3'
              geometry={nodes.bodymesh_3.geometry}
              material={materials['Material.006']}
              skeleton={nodes.bodymesh_3.skeleton}
            />
          </group>
          <skinnedMesh
            name='hair'
            geometry={nodes.hair.geometry}
            material={materials['Material.001']}
            skeleton={nodes.hair.skeleton}
          />
          <skinnedMesh
            name='head'
            geometry={nodes.head.geometry}
            material={materials['Face.002']}
            skeleton={nodes.head.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/abelB.glb');
