/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/abel.glb 
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/abel.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name='beanie001'
            geometry={nodes.beanie001.geometry}
            material={nodes.beanie001.material}
            skeleton={nodes.beanie001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/abel.glb');
