/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/capo-animation.glb 
*/

import React, { RefObject, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group } from "three";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

interface ModelProps {
  // props: any;
}
const Amin = ({}: ModelProps): JSX.Element => {
  const group: RefObject<Group> = useRef<Group>(null);
  // const { nodes, materials, animations } = useGLTF('/capo-animation.glb')
  const gltf = useLoader(GLTFLoader, `/capo-animation.glb`);
  const { actions } = useAnimations(gltf.animations, group);
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={gltf.nodes.mixamorig9Hips} />
        </group>
      </group>
    </group>
  );
};
export default Amin;
useGLTF.preload("/capo-animation.glb");
