/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/loco.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/loco.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[0, 0, 0]} scale={0.001}>
          <primitive object={nodes.mixamorig10Hips} />
          <skinnedMesh
            name="Ch28_Body"
            geometry={nodes.Ch28_Body.geometry}
            material={materials.Ch28_body}
            skeleton={nodes.Ch28_Body.skeleton}
          />
          <skinnedMesh
            name="Ch28_Eyelashes"
            geometry={nodes.Ch28_Eyelashes.geometry}
            material={materials.Ch28_hair}
            skeleton={nodes.Ch28_Eyelashes.skeleton}
          />
          <skinnedMesh
            name="Ch28_Hair"
            geometry={nodes.Ch28_Hair.geometry}
            material={materials.Ch28_hair}
            skeleton={nodes.Ch28_Hair.skeleton}
          />
          <skinnedMesh
            name="Ch28_Hoody"
            geometry={nodes.Ch28_Hoody.geometry}
            material={materials.Ch28_body}
            skeleton={nodes.Ch28_Hoody.skeleton}
          />
          <skinnedMesh
            name="Ch28_Pants"
            geometry={nodes.Ch28_Pants.geometry}
            material={materials.Ch28_body}
            skeleton={nodes.Ch28_Pants.skeleton}
          />
          <skinnedMesh
            name="Ch28_Sneakers"
            geometry={nodes.Ch28_Sneakers.geometry}
            material={materials.Ch28_body}
            skeleton={nodes.Ch28_Sneakers.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/loco.glb");
